Исправлена опечатка и несколько кавычек
progit/progit2-ru pull request #337
Opened 2021-01-15 06:40 UTC by SergeiKuznetsov

2021-01-17 10:38 UTC, Morganov requested changes

2021-01-17 10:38 UTC, Morganov commented on book/A-git-in-other-environments/sections/guis.asc
> +Введите сообщение коммита, выберете файлы для включения в коммит и нажмите кнопку «Commit» (ctrl-enter or ⌘-enter).
```suggestion
Введите сообщение коммита, выберете файлы для включения в коммит и нажмите кнопку «Commit» (ctrl-enter или ⌘-enter).
```

2021-01-17 10:38 UTC, Morganov commented on book/A-git-in-other-environments/sections/visualstudio.asc
> +Это центр управления Git; когда вы _пишете_ код, вы, вероятно, проводите большую часть своего времени на странице «Changes» («Изменения»), но когда приходит время получать изменения, сделанные вашими
Везде по тексту книги используется перевод "Ветка", а не "Ветвь".
```suggestion
Это центр управления Git; когда вы _пишете_ код, вы, вероятно, проводите большую часть своего времени на странице «Changes» («Изменения»), но когда приходит время получать изменения, сделанные вашими коллегами по работе, вам необходимо использовать страницы "Unsynced Commits" ("Несинхронизированные коммиты") и «Branches» («Ветки»).
```

2021-01-17 10:38 UTC, Morganov commented on book/B-embedding-git/sections/jgit.asc
> +* "Поваренная книга" JGit, расположенная по адресу https://github.com/centic9/jgit-cookbook[], включает в себя много готовых «рецептов» использования JGit для решения тех или иных задач.
Здесь, "рецепт" иеет такой же перносный смысл, как и "Поавренная книга".
```suggestion
* ``Поваренная книга'' JGit, расположенная по адресу https://github.com/centic9/jgit-cookbook[], включает в себя много готовых ``рецептов'' использования JGit для решения тех или иных задач.
```

2021-01-17 10:38 UTC, Morganov commented on book/toc.asc
> -{{ toc }}
Какой смысл оставлять пустой файл?

2021-01-17 10:38 UTC, Morganov commented on book/07-git-tools/sections/advanced-merging.asc
> +Для примера предположим, что вы создали ветку «release» и проделали в ней некоторую работу, которую когда-то впоследствии захотите слить обратно в «master».
```suggestion
Для примера предположим, что вы создали ветку `release` и проделали в ней некоторую работу, которую когда-то впоследствии захотите слить обратно в `master`.
```

2021-01-17 10:38 UTC, Morganov commented on book/07-git-tools/sections/advanced-merging.asc
> +Тем временем в «master» были сделаны некоторые исправления, которые необходимо перенести также в вашу ветку «release».
```suggestion
Тем временем в `master` были сделаны некоторые исправления, которые необходимо перенести также в вашу ветку `release`.
```

2021-01-17 10:38 UTC, Morganov commented on book/06-github/sections/2-contributing.asc
> +Исторически так сложилось, что англоязычный термин «fork»  (создание ветвления проекта) имел негативный контекстный смысл, данный термин означал, что кто-то повёл или ведёт проект с открытым исходным
```suggestion
Исторически так сложилось, что англоязычный термин «fork» (создание ветвления проекта) имел негативный контекстный смысл, данный термин означал, что кто-то повёл или ведёт проект с открытым исходным кодом в другом, отличном от оригинала, направлении, иногда данный термин так же означал создание конкурирующего проекта с раздельными авторами.
```

2021-01-17 10:38 UTC, Morganov commented on book/06-github/sections/2-contributing.asc
> +В контексте GitHub, «fork»  (создание ветвления проекта) просто означает создание ветвления проекта в собственном пространстве имён, что позволяет вносить публичные изменения и делать свой собственны
```suggestion
В контексте GitHub, «fork» (создание ветвления проекта) просто означает создание ветвления проекта в собственном пространстве имён, что позволяет вносить публичные изменения и делать свой собственный вклад в более открытом виде.
```

2021-01-17 10:38 UTC, Morganov commented on book/06-github/sections/2-contributing.asc
> +Для того, чтобы создать ответвление проекта (fork), зайдите на страницу проекта и нажмите кнопку «Создать ответвление» («Fork»), которая расположена в правом верхнем углу.
```suggestion
Для того, чтобы создать ответвление проекта, зайдите на страницу проекта и нажмите кнопку «Создать ответвление» («Fork»), которая расположена в правом верхнем углу.
```

2021-01-17 10:38 UTC, Morganov commented on book/06-github/sections/2-contributing.asc
> +Возможно, ваш следующий вопрос будет «Как мне сослаться на предыдущий запрос слияния?».
Если при цитировании взятый в кавычки текст заканчивается точкой, то её выносят из текста и ставят после закрывающей кавычки. Если текст заканчивается многоточием либо вопросительным или восклицательным знаком, причём цитата является самостоятельным предложением (а не членом предложения, в которое включена), то точка после кавычки не ставится.
```suggestion
Возможно, ваш следующий вопрос будет: «Как мне сослаться на предыдущий запрос слияния?»
```

2021-01-17 10:38 UTC, Morganov commented on book/06-github/sections/2-contributing.asc
> +Для Проблемы или запроса слияния в полях описания, комментария, комментария кода и других вы можете использовать так называемую «Дополненную разметку GitHub».
Здесь "проблема" и "запрос слияния" - термины.
```suggestion
Для «проблемы» или «запроса слияния» в полях описания, комментария, комментария кода и других вы можете использовать так называемую «Дополненную разметку GitHub».
```

2021-01-17 10:42 UTC, Morganov commented
Хотелось бы добавить, что неплохо было бы иметь дополение в `TRANSLATION_NOTES.asc`, поясняющее в каких случаях использовать какие кавычки.

2021-01-17 10:48 UTC, SergeiKuznetsov commented on book/01-introduction/sections/about-version-control.asc
> +=== О системе контроля версий
Один из предыдущих редакторов сохранил файл с окончаниями строк LFCR
Я просто вернул как было LF.

2021-01-17 10:55 UTC, SergeiKuznetsov commented on C-git-commands.asc
> +Но такой подход «размазал» описания команд по всей книге.
asciidoc формат двойных кавычек это код для вставки английских двойных кавычек. В России они не используются. Машинописные у нас только в коде программ и в командах. Во всех русских текстах принято использовать кавычки-ёлочки «»
Это элементарные правила типографики. И это не спец символы какие-то, а привычные кавычки. Они со времён MS DOS в стандарных символах CP1251 даже присутствуют.

2021-01-17 11:05 UTC, SergeiKuznetsov commented
@Morganov  Ещё раз: 
В текстах принято ставить кавычки ёлочки. 
В коде — машинописные двойные или одинарные кавычки.

Можно увидеть место, где не заменил? Я проверил все файлы в два захода. В первом коммите asciidoc-кавычки убрал, а во втором подчистил машинописные.

2021-01-17 11:23 UTC, SergeiKuznetsov commented on book/01-introduction/sections/basics.asc
> +Эту область ещё называют «индекс», однако называть её stage-область также общепринято.
Надо будет свериться с официальным переводом консольного Git.

2021-01-17 11:32 UTC, SergeiKuznetsov commented on book/03-git-branching/sections/basic-branching-and-merging.asc
> +Если вы хотите использовать инструмент слияния не по умолчанию (в данном случае Git выбрал `opendiff`, поскольку команда запускалась на Mac), список всех поддерживаемых инструментов представлен вверх
Да, надо поправить. Кстати, с нормальными кавычками текст читается легче, и такие опечатки легче заметить уже.

2021-01-17 11:45 UTC, SergeiKuznetsov commented on book/06-github/sections/1-setting-up-account.asc
> +В качестве дополнительной меры безопасности, вы можете настроить "Двухфакторную аутентификацию" («Two-factor Authentication» или «2FA»).
Такие кавычки я тоже менял, но вторым проходом. Чтобы не мешать всё в кучу.

2021-01-17 11:52 UTC, SergeiKuznetsov commented on book/08-customizing-git/sections/config.asc
> +Каждый из этих «уровней» (системный, глобальный, локальный) переопределяет значения предыдущего уровня, например, значения из `.git/config` важнее значений из `/etc/gitconfig`.
Тут наверное надо убрать кавычки. Но уж точно английские там неуместны.

2021-01-17 12:01 UTC, SergeiKuznetsov commented on book/09-git-and-other-scms/sections/client-hg.asc
> +Git и Mercurial довольно похожи, их относительно просто можно «подружить».
Поэтому и кавычки. В чём проблема?

2021-01-17 12:04 UTC, SergeiKuznetsov commented on book/10-git-internals/sections/maintenance.asc
> +Однако, если у вас накопилось слишком много «рыхлых» объектов (не в pack-файлах), или, наоборот, отдельных pack-файлов, Git запускает полноценный сборщик -- `git gc` (здесь «gc» это сокращение от "ga
Это не русские. Я их упустил видимо.

2021-01-17 12:12 UTC, SergeiKuznetsov commented on book/B-embedding-git/sections/jgit.asc
> +* "Поваренная книга" JGit, расположенная по адресу https://github.com/centic9/jgit-cookbook[], включает в себя много готовых «рецептов» использования JGit для решения тех или иных задач.
Значит убрать кавычки

2021-01-17 12:14 UTC, SergeiKuznetsov commented on book/toc.asc
> -{{ toc }}
Это удаление файла

2021-01-17 12:27 UTC, SergeiKuznetsov commented
@Morganov Поправил все замечания

2021-01-17 14:31 UTC, Morganov requested changes

2021-01-17 14:31 UTC, Morganov commented on book/01-introduction/sections/about-version-control.asc
> +=== О системе контроля версий
👍

2021-01-17 14:31 UTC, Morganov commented on book/06-github/sections/1-setting-up-account.asc
> +.Ссылка «Настройка учётной записи»(«Account settings»)
```suggestion
.Ссылка «Настройка учётной записи» («Account settings»)
```

2021-01-17 14:31 UTC, Morganov commented on book/06-github/sections/1-setting-up-account.asc
> +Выберите секцию слева под названием «Ключи SSH»(«SSH keys»).
```suggestion
Выберите секцию слева под названием «Ключи SSH» («SSH keys»).
```

2021-01-17 14:31 UTC, Morganov commented on book/06-github/sections/1-setting-up-account.asc
> +.Ссылка («SSH keys»)
```suggestion
.Ссылка «Ключи SSH» («SSH** keys»)
```

2021-01-17 14:31 UTC, Morganov commented on book/06-github/sections/1-setting-up-account.asc
> +image::images/ssh-keys.png["Ссылка («SSH keys»)"]
```suggestion
image::images/ssh-keys.png["Ссылка «Ключи SSH» («SSH keys»)"]
```

2021-01-17 14:31 UTC, Morganov commented on book/06-github/sections/1-setting-up-account.asc
> +В качестве дополнительной меры безопасности, вы можете настроить "Двухфакторную аутентификацию" («Two-factor Authentication» или «2FA»).
Смотрю общий diff - не вижу "второго прохода".

2021-01-17 14:31 UTC, Morganov commented on book/A-git-in-other-environments/sections/visualstudio.asc
> +Это центр управления Git; когда вы _пишете_ код, вы, вероятно, проводите большую часть своего времени на странице «Changes» («Изменения»), но когда приходит время получать изменения, сделанные вашими
```suggestion
Это центр управления Git; когда вы _пишете_ код, вы, вероятно, проводите большую часть своего времени на странице «Changes» («Изменения»), но когда приходит время получать изменения, сделанные вашими коллегами по работе, вам необходимо использовать страницы «Unsynced Commits» («Несинхронизированные коммиты») и «Branches» («Ветки»).
```

2021-01-17 14:31 UTC, Morganov commented on book/B-embedding-git/sections/jgit.asc
> +* "Поваренная книга" JGit, расположенная по адресу https://github.com/centic9/jgit-cookbook[], включает в себя много готовых рецептов использования JGit для решения тех или иных задач.
```suggestion
* «Поваренная книга» JGit, расположенная по адресу https://github.com/centic9/jgit-cookbook[], включает в себя много готовых рецептов использования JGit для решения тех или иных задач.
```

2021-01-17 14:53 UTC, Morganov commented
> Можно увидеть место, где не заменил? Я проверил все файлы в два захода. В первом коммите asciidoc-кавычки убрал, а во втором подчистил машинописные.

Да, вот список файлов с номерами строк, где остались "лапки"

> ./book/A-git-in-other-environments/sections/guis.asc:85
./book/A-git-in-other-environments/sections/guis.asc:113
./book/A-git-in-other-environments/sections/guis.asc:139
./book/A-git-in-other-environments/sections/zsh.asc:49
./book/02-git-basics/sections/viewing-history.asc:221 
./book/02-git-basics/sections/viewing-history.asc:242
./book/08-customizing-git/sections/config.asc:392
./book/09-git-and-other-scms/sections/client-bzr.asc:89
./book/09-git-and-other-scms/sections/client-bzr.asc:90
./book/09-git-and-other-scms/sections/client-bzr.asc:98
./book/09-git-and-other-scms/sections/import-bzr.asc:133
./book/09-git-and-other-scms/sections/client-hg.asc:10
./book/09-git-and-other-scms/sections/client-hg.asc:41
./book/09-git-and-other-scms/sections/client-hg.asc:97
./book/09-git-and-other-scms/sections/client-hg.asc:125
./book/09-git-and-other-scms/sections/client-hg.asc:237
./book/09-git-and-other-scms/sections/client-svn.asc:7
./book/09-git-and-other-scms/sections/client-svn.asc:113
./book/09-git-and-other-scms/sections/client-svn.asc:374
./book/09-git-and-other-scms/sections/client-svn.asc:481
./book/09-git-and-other-scms/sections/client-p4.asc:166
./book/09-git-and-other-scms/sections/client-p4.asc:370
./book/09-git-and-other-scms/sections/client-p4.asc:646
./book/06-github/sections/3-maintaining.asc:180
./book/06-github/sections/3-maintaining.asc:190
./book/06-github/sections/1-setting-up-account.asc:47
./book/06-github/sections/1-setting-up-account.asc:66
./book/06-github/sections/2-contributing.asc:131
./book/07-git-tools/sections/credentials.asc:11
./book/07-git-tools/sections/rerere.asc:145
./book/07-git-tools/sections/replace.asc:6
./book/07-git-tools/sections/replace.asc:153

2021-01-17 20:07 UTC, SergeiKuznetsov commented
„лапки“ — вот это лапки. Таких не искал и сейчас вроде нет.
“английские двойные” тоже не искал. Сейчас вижу ещё одно место с ними.
Кавычки в виде кодов пропускал в файлах с неполным переводом

2021-01-18 06:12 UTC, Morganov commented
Исправьте образовавшиеся конфлифкты и замечания к текущим изменениям. Думаю, этого будет достаточно на текущий момент.
Не стоит на долго откладывать внесение предложенных изменений.

2021-01-18 22:02 UTC, Morganov requested changes

2021-01-18 22:11 UTC, SergeiKuznetsov commented on .mailmap
> +Jean-Noël Avila <jn.avila@free.fr>
Заменять в списке мыло безымянных контрибуторов на их реальное имя. 
Файл я взял из английского репозитория и добавил туда строчку 
`Sanders Kleinfeld <sanders@oreilly.com>`

2021-01-18 22:14 UTC, SergeiKuznetsov commented on book/02-git-basics/sections/recording-changes.asc
> +Символ (`+*+`) соответствует 0 или более символам; последовательность `[abc]` -- любому символу из указанных в скобках (в данном примере a, b или c); знак вопроса (`?`) соответствует одному символу;
Пришлось добавить это экранирование, иначе звёздочка воспринималась как управляющий код asciicode и заменялась на тег <strong>
И в нескольких других местах подобная проблема вылезла.

2021-01-18 22:19 UTC, SergeiKuznetsov commented on book/02-git-basics/sections/recording-changes.asc
> +Символ (`+*+`) соответствует 0 или более символам; последовательность `[abc]` -- любому символу из указанных в скобках (в данном примере a, b или c); знак вопроса (`?`) соответствует одному символу;
После обновления зависимостей такое началось?

2021-01-18 22:38 UTC, SergeiKuznetsov commented on book/09-git-and-other-scms/sections/client-svn.asc
> +Разумеется, при переносе реального Subversion репозитория нужно будет заменить `\file:///tmp/test-svn` на настоящий URL:
Без этого бекслеша компилирует криво
![image](https://user-images.githubusercontent.com/13728212/104968309-e5fc1400-59fe-11eb-9b8a-cf046f9569e2.png)
Подсмотрел этот приём в английской книге. https://github.com/progit/progit2/pull/1564

2021-01-18 22:39 UTC, SergeiKuznetsov commented on book/10-git-internals/sections/environment.asc
> +Если переменная `GIT_GLOB_PATHSPECS` установлена в 1, то специальные символы интерпретируются как шаблон (поведение по умолчанию); если же `GIT_NOGLOB_PATHSPECS` установлена в 1, то специальные симво
Прошу почитать тут https://github.com/progit/progit2/pull/1564
Без экранирования собирает сейчас криво.

2021-01-18 22:41 UTC, SergeiKuznetsov commented on locale/attributes-ru.adoc
> +// Russian translation, courtesy of Alexander Zobkov <alexander.zobkov@gmail.com>
Файл лежит в отдельном репозитории, чтобы оттуда скачивали и использовали в своих книгах.
Да и вдруг мы свой вариант локализации захотим?

2021-01-18 22:42 UTC, SergeiKuznetsov commented on book/06-github/sections/3-maintaining.asc
> +Все проекты на GitHub доступны как по HTTP `\https://github.com/<user>/<project_name>`, так  по SSH `\git@github.com:<user>/<project_name>`.
Ответил выше.

2021-01-18 22:58 UTC, SergeiKuznetsov commented
Пора уже смержить мои правки. Почти все замечания это не мои ошибки, а предложение новых доработок.
Работы тут ещё много, но приходится разрешать новые конфликты вместо реальных проблем.

2021-01-19 00:18 UTC, SergeiKuznetsov commented on book/09-git-and-other-scms/sections/client-svn.asc
> +Разумеется, при переносе реального Subversion репозитория нужно будет заменить `\file:///tmp/test-svn` на настоящий URL:
Конкретнее тут https://github.com/progit/progit2/pull/1564/commits/c6c44943769259dac9f94cb0c38c0562a619e876#r530252339

2021-01-19 00:20 UTC, SergeiKuznetsov commented on book/09-git-and-other-scms/sections/client-svn.asc
> +Разумеется, при переносе реального Subversion репозитория нужно будет заменить `\file:///tmp/test-svn` на настоящий URL:
И тут https://github.com/asciidoctor/asciidoctor/issues/3864
Я взял первое попавшееся решение. В дальнейшем возможно переделать более корректно.

2021-01-19 00:37 UTC, SergeiKuznetsov commented on book/10-git-internals/sections/environment.asc
> +Если переменная `GIT_GLOB_PATHSPECS` установлена в 1, то специальные символы интерпретируются как шаблон (поведение по умолчанию); если же `GIT_NOGLOB_PATHSPECS` установлена в 1, то специальные симво
https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/#escaping-substitutions

2021-01-20 21:30 UTC, Morganov requested changes

2021-01-20 21:30 UTC, Morganov commented on book/02-git-basics/sections/recording-changes.asc
> +Символ (`+*+`) соответствует 0 или более символам; последовательность `[abc]` -- любому символу из указанных в скобках (в данном примере a, b или c); знак вопроса (`?`) соответствует одному символу;
Хм, в англ версии была бы такая же проблема.
Думаю, стоит оставить так и создать issue, чтобы с этим разобраться позже.

2021-01-20 21:30 UTC, Morganov commented on locale/attributes-ru.adoc
> +// Russian translation, courtesy of Alexander Zobkov <alexander.zobkov@gmail.com>
Пожалуйста, удалите этот файл. Если он используется при сборке книги, то создайте отдельный ПР.

2021-01-20 23:10 UTC, SergeiKuznetsov commented on locale/attributes-ru.adoc
> +// Russian translation, courtesy of Alexander Zobkov <alexander.zobkov@gmail.com>
Удалил файл. Вернул ручные вставки терминов, как раньше.

2021-01-20 23:25 UTC, SergeiKuznetsov commented on book/02-git-basics/sections/recording-changes.asc
> +Символ (`+*+`) соответствует 0 или более символам; последовательность `[abc]` -- любому символу из указанных в скобках (в данном примере a, b или c); знак вопроса (`?`) соответствует одному символу;
Как раз в английской версии с аналогичной проблемой и столкнулись.  
Методов экранирования правда несколько. Надо выбрать какой-то один.
Например (\`{empty}*\`)

2021-01-21 20:50 UTC, Morganov commented
> 
> 
> Пора уже смержить мои правки. Почти все замечания это не мои ошибки, а предложение новых доработок.
> Работы тут ещё много, но приходится разрешать новые конфликты вместо реальных проблем.

Правки мержатся по мере их готовности и полноты, а не по времени, в течение которого вы не можете привести их в порядок.
Если вы вносите изменение в предложение, будте добры прочитать его и, по возможности, исправить имеющиеся ошибки.

Чтобы избежать длительного ревью:
- Воздержитесь от объёмных правок. Если это не представляется возможным, разделите изменения соответственно разделам или главам книги. Можно создать несколько ПР с правками к разным главам и дорабатывать их независимо.
- Не включайте разнотипные изменения в один ПР. Часто слияние задерживается только из-за того, что есть замечания к одного типа изменениям. В вашем случае это добавление неиспользуемого файла.
- Используйте дополнительную функциональность GitHub (некоторые взможности приведены в [книге](https://git-scm.com/book/ru/v2/GitHub-%D0%92%D0%BD%D0%B5%D1%81%D0%B5%D0%BD%D0%B8%D0%B5-%D1%81%D0%BE%D0%B1%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D0%BE%D0%B3%D0%BE-%D0%B2%D0%BA%D0%BB%D0%B0%D0%B4%D0%B0-%D0%B2-%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D1%8B)), чтобы сделать процесс вашей работы над изменениями большого объёма более прозрачным.

Всё это может значительно ускорить процесс ревью. Цените чужое время.

2021-01-21 20:52 UTC, Morganov approved these changes

2021-01-21 20:52 UTC, merged

2021-01-21 21:52 UTC, SergeiKuznetsov commented
Спасибо за замечания. Я сам не ожидал, что все правки свалятся в один ПР. Видимо потому, что не создал отдельную ветку для каждого изменения. 

Насчёт неиспользуемого файла не понял. Он как раз очень нужен и использовался для локализации.