Синхронизация ссылок с английским оригиналом
progit/progit2-ru pull request #348
Opened 2021-01-25 00:54 UTC by SergeiKuznetsov

Изменил только то, что поменялось в оригинальной книге.
В основном сайты перешли на https
Некоторые поменяли URL
Раздел «Основы Git» переименован во «Что такое Git?»

2021-01-27 18:14 UTC, Morganov requested changes

2021-01-27 18:14 UTC, Morganov commented on LICENSE.asc
> +Это произведение распространяется по свободной лицензии Creative Commons Attribution-NonCommercial-ShareAlike 3.0. Ознакомиться с текстом лицензии вы можете на сайте https://creativecommons.org/licen
Добавьте переносы строк.

2021-01-27 18:14 UTC, Morganov commented on book/02-git-basics/sections/recording-changes.asc
> +Редактор устанавливается переменной окружения `EDITOR` -- обычно это vim или emacs, хотя вы можете установить любой другой с помощью команды `git config --global core.editor`, как было показано в гла
Как устанавливается редактор, описано в "Выбор редактора". Верните назад.

2021-01-27 18:14 UTC, Morganov commented on book/04-git-server/sections/gitlab.asc
> +Если у пользователя +jane+ есть проект +project+, адрес этого проекта будет `\http://server/jane/project`.
```suggestion
Если у пользователя +jane+ есть проект +project+, адрес этого проекта будет `http://server/jane/project`.
```

2021-01-27 18:14 UTC, Morganov commented on book/04-git-server/sections/gitlab.asc
> +Каждая группа имеет пространство имён проектов (так же как и пользователи), так что если в группе +training+ есть проект +materials+, его адрес будет `\http://server/training/materials`.
```suggestion
Каждая группа имеет пространство имён проектов (так же как и пользователи), так что если в группе +training+ есть проект +materials+, его адрес будет `http://server/training/materials`.
```

2021-01-27 18:20 UTC, SergeiKuznetsov commented on book/02-git-basics/sections/recording-changes.asc
> +Редактор устанавливается переменной окружения `EDITOR` -- обычно это vim или emacs, хотя вы можете установить любой другой с помощью команды `git config --global core.editor`, как было показано в гла
Мы делаем перевод оригинала или свою версию книги? Согласен, что ссылку лучше бы поменять. Но сначала в оригинале, а потом уже тут.

2021-01-27 18:45 UTC, SergeiKuznetsov commented on LICENSE.asc
> +Это произведение распространяется по свободной лицензии Creative Commons Attribution-NonCommercial-ShareAlike 3.0. Ознакомиться с текстом лицензии вы можете на сайте https://creativecommons.org/licen
OK

2021-01-27 18:50 UTC, SergeiKuznetsov commented on book/02-git-basics/sections/recording-changes.asc
> +Редактор устанавливается переменной окружения `EDITOR` -- обычно это vim или emacs, хотя вы можете установить любой другой с помощью команды `git config --global core.editor`, как было показано в гла
This is set by your shell's `EDITOR` environment variable -- usually vim or emacs, although you can configure it with whatever you want using the `git config --global core.editor` command as you saw in <<ch01-getting-started#ch01-getting-started>>.(((editor, changing default)))(((git commands, config)))

2021-01-27 18:52 UTC, SergeiKuznetsov commented on book/04-git-server/sections/gitlab.asc
> +Если у пользователя +jane+ есть проект +project+, адрес этого проекта будет `\http://server/jane/project`.
OK

2021-01-27 18:53 UTC, SergeiKuznetsov commented on book/04-git-server/sections/gitlab.asc
> +Каждая группа имеет пространство имён проектов (так же как и пользователи), так что если в группе +training+ есть проект +materials+, его адрес будет `\http://server/training/materials`.
OK

2021-01-28 21:44 UTC, Morganov approved these changes

2021-01-28 21:44 UTC, Morganov commented on book/02-git-basics/sections/recording-changes.asc
> +Редактор устанавливается переменной окружения `EDITOR` -- обычно это vim или emacs, хотя вы можете установить любой другой с помощью команды `git config --global core.editor`, как было показано в гла
👍

2021-01-28 21:44 UTC, merged