Опечатки и сверка текста с оригиналом
progit/progit2-ru pull request #350
Opened 2021-01-25 03:55 UTC by SergeiKuznetsov

1991-2002 гг. Дефис-минус заменён на среднее тире. 
1991–2002 гг. В английской версии это уже сделано.

сл**э**ш — заменён на сл**е**ш, так грамотнее.

2021-01-25 04:45 UTC, SergeiKuznetsov commented
Среднее тире заменил на --
т. к. в русской типографике его используют только внутри диапазонов типа 1991–2002

2021-01-26 02:24 UTC, SergeiKuznetsov commented
Разряды больших чисел у нас отбиваются не запятой, а тонкой шпацией. Она похожа на пробел, но в два раза уже.
Вот как выглядит с неразрывным пробелом:
![image](https://user-images.githubusercontent.com/13728212/105787048-98038500-5f97-11eb-84b9-b917939fa321.png)
А вот так с [узким неразрывным пробелом](https://unicode-table.com/ru/202F/)
![image](https://user-images.githubusercontent.com/13728212/105790466-def47900-5f9d-11eb-9838-1563d5a12168.png)

2021-01-31 08:54 UTC, Morganov requested changes

2021-01-31 20:33 UTC, SergeiKuznetsov commented on TRANSLATION_NOTES.asc
> +Вариант перевода тег относится к html-тегам. В Git это именно метка, маркер содержимого, а не элемент разметки.
В данном случае метка больше подходит по смыслу. И в терминологии систем управления версиями принято говорить метка.
Пример: https://www.microsoft.com/en-us/language/Search?&searchTerm=tag&langID=635&Source=true&productid=undefined

2021-01-31 20:38 UTC, SergeiKuznetsov commented on book/01-introduction/sections/what-is-git.asc
> +Мы подошли к трём основным секциям проекта Git: рабочая копия (working tree), область подготовленных изменений (staging area) и директория Git (Git directory).
1. В индексе могут быть не файлы, а их изменённые фрагменты. Можно проиндексировать часть изменений, а часть оставить в рабочей копии пока.
2. Авторы посчитали, что такой порядок правильней. Я сверялся с оригиналом, а не правил, потому что мне так захотелось. Хотя тоже считаю что в английской версии стало логичнее. Нам надо только привести в порядок у себя.

2021-01-31 20:46 UTC, SergeiKuznetsov commented on TRANSLATION_NOTES.asc
> +https://ilyabirman.ru/projects/typography-layout/
https://github.com/neochief/birman-typography-layouts-for-ubuntu

2021-01-31 20:49 UTC, Morganov commented on TRANSLATION_NOTES.asc
> +Вариант перевода тег относится к html-тегам. В Git это именно метка, маркер содержимого, а не элемент разметки.
В таблице по ссылке первым идёт "тег" :)
![Screenshot_1](https://user-images.githubusercontent.com/16842235/106397294-b1845100-641d-11eb-8e80-d5ac5d94b475.png)

Так как "тег"и "метка", суть одно и тоже, нет смысла усложнять. Так как команды Git вводятся на англ. языке, то использовать более созвучное слово предпочтительнее, потому что цель книги - как можно ближе познакомить читателя с Git.

2021-01-31 21:18 UTC, Morganov commented on book/01-introduction/sections/what-is-git.asc
> +Мы подошли к трём основным секциям проекта Git: рабочая копия (working tree), область подготовленных изменений (staging area) и директория Git (Git directory).
>     1. В индексе могут быть не файлы, а их изменённые фрагменты. Можно проиндексировать часть изменений, а часть оставить в рабочей копии пока.

Фрагменты файлов, а точнее diff, может быть только в pack-файле. При индексации части изменений (hunk), файл добавляется целиком, просто остальные изменения игнорируются.
Это легко проверить:

1. Посмотреть список файлов в индексе `git ls-files -s`. Думаю, вас удивит их количество.
2. Посмотреть содержимое файла в индексе `git cat-file -p SHA`.

Если в проиндексированный файл добавить ещё изменений, то в понимании Git это будет новая версия файла.

>     2. Авторы посчитали, что такой порядок правильней. Я сверялся с оригиналом, а не правил, потому что мне так захотелось. Хотя тоже считаю что в английской версии стало логичнее. Нам надо только привести в порядок у себя.

Ок.

2021-01-31 21:38 UTC, Morganov commented on TRANSLATION_NOTES.asc
> +https://ilyabirman.ru/projects/typography-layout/
> 
> 
> https://github.com/neochief/birman-typography-layouts-for-ubuntu

Думаю, это достойно переместиться в Wiki

2021-02-01 01:39 UTC, SergeiKuznetsov commented on TRANSLATION_NOTES.asc
> +Вариант перевода тег относится к html-тегам. В Git это именно метка, маркер содержимого, а не элемент разметки.
Tag часто встречается в разных продуктах.  Но в git это именно метка.

2021-02-01 01:50 UTC, SergeiKuznetsov commented on book/01-introduction/sections/what-is-git.asc
> +Мы подошли к трём основным секциям проекта Git: рабочая копия (working tree), область подготовленных изменений (staging area) и директория Git (Git directory).
Тогда может «область индексированных файлов»? Или просто индекс.

2021-02-01 04:25 UTC, SergeiKuznetsov commented on TRANSLATION_NOTES.asc
> +Вариант перевода тег относится к html-тегам. В Git это именно метка, маркер содержимого, а не элемент разметки.
![image](https://user-images.githubusercontent.com/13728212/106414761-de108b00-6466-11eb-91bf-0b326d5e65e1.png)

2021-02-01 04:27 UTC, SergeiKuznetsov commented on TRANSLATION_NOTES.asc
> +Вариант перевода тег относится к html-тегам. В Git это именно метка, маркер содержимого, а не элемент разметки.
TortoiseGit
![image](https://user-images.githubusercontent.com/13728212/106414888-347dc980-6467-11eb-9305-8a98d0a8bb0c.png)

2021-02-01 04:45 UTC, SergeiKuznetsov commented on TRANSLATION_NOTES.asc
> +Слово «директория» -- это вульгарная калька с английского слова directory, которое в русскоязычной документации (и литературе)
OK

2021-02-01 05:27 UTC, SergeiKuznetsov commented on TRANSLATION_NOTES.asc
> +Никогда не склоняйте и не добавляйте суффиксы к словам на латинице ни через пробел, ни через дефис, ни через уродливый апостроф.
OK

2021-02-01 05:43 UTC, SergeiKuznetsov commented on book/01-introduction/sections/what-is-git.asc
> +1. Изменяете файлы в вашей рабочей директории.
OK

2021-02-01 05:46 UTC, SergeiKuznetsov commented on TRANSLATION_NOTES.asc
> +https://ilyabirman.ru/projects/typography-layout/
OK

2021-02-01 20:42 UTC, SergeiKuznetsov commented on book/09-git-and-other-scms/sections/client-svn.asc
> +Он существует уже более десяти лет, и большую часть этого времени был _де-факто_ единственной системой контроля версий для проектов с открытым исходным кодом.
OK

2021-02-01 20:52 UTC, SergeiKuznetsov commented on C-git-commands.asc
> +Команда `git cherry-pick` используется для того чтобы взять изменения, внесённые каким-либо коммитом, и попытаться применить их заново в виде нового коммита в текущей ветке.
Не вижу проблемы. Мы же у команды commit тоже не уточняем, где будет создан новый коммит.
А тут именно говорится, что создаётся новый коммит. Новый коммит всегда наверху, точнее в конце.
Откуда тут могут возникнуть непонятки? Тут скорее от слова наверху будут неясности.

2021-02-01 21:33 UTC, SergeiKuznetsov commented on C-git-commands.asc
> +Команда `git cherry-pick` используется для того чтобы взять изменения, внесённые каким-либо коммитом, и попытаться применить их заново в виде нового коммита в текущей ветке.
Переформулировал этот параграф:

Команда git cherry-pick берёт изменения, вносимые одним коммитом, и пытается повторно применить их в виде нового коммита в текущей ветке.
Эта возможность полезна в ситуации, когда нужно забрать парочку коммитов из другой ветки, а не сливать ветку целиком со всеми внесенными в нее изменениями.

Этот процесс описан и показан в разделе <<ch05-distributed-git#r_rebase_cherry_pick>> главы 5.

2021-02-01 21:42 UTC, SergeiKuznetsov commented on book/01-introduction/sections/what-is-git.asc
> +Мы подошли к трём основным секциям проекта Git: рабочая копия (working tree), область подготовленных изменений (staging area) и директория Git (Git directory).
Область индексирования — коротко и ясно считаю.

2021-02-03 06:52 UTC, SergeiKuznetsov commented on TRANSLATION_NOTES.asc
> +Вариант перевода тег относится к html-тегам. В Git это именно метка, маркер содержимого, а не элемент разметки.
Ладно. Пусть будет тег.
Но потом нужно провести ревизию и привести к единообразию по всей книге.

2021-02-03 06:54 UTC, SergeiKuznetsov commented on C-git-commands.asc
> +Команда `git cherry-pick` используется для того чтобы взять изменения, внесённые каким-либо коммитом, и попытаться применить их заново в виде нового коммита в текущей ветке.
Хороший перевод термина cherry-pick — отбор.

2021-02-04 11:47 UTC, Morganov requested changes

2021-02-04 11:47 UTC, Morganov commented on TRANSLATION_NOTES.asc
> +Вместо того, чтобы облегчить, вы затрудняете чтение.
В русском языке существует правило, запрещающее склонять слова на латинице. Лучше сослаться на него.
```suggestion
Согласно правилам русского языка слова на латинице, такие как Git или GitHub, не склоняются.
Поэтому, не добавляйте суффиксы к таким словам ни через пробел, ни через дефис, ни через апостроф.

Неправильно: **GitHub’овский** запрос на слияние
Правильно: запрос на слияние на GitHub

Указанные конструкции не только противоречат правилам, но и затрудняют чтение.
```

2021-02-04 11:47 UTC, Morganov commented on TRANSLATION_NOTES.asc
> +stashes -- припрятанные
`stashes` - может быть и глаголом, относящимся к существительному в третьем лице единственного числа.
Например:
`Git stashes your work ....` - здесь употребляется как глагол.
`Git can list all saved stashes` - здесь существительно во множественном числе.

2021-02-04 11:47 UTC, Morganov commented on book/01-introduction/sections/what-is-git.asc
> +Мы подошли к трём основным секциям проекта Git: рабочая копия (working tree), область индексирования (staging area) и каталог Git (Git directory).
Может просто "индекс" вместо "область индексирования"?
Так как "staging area" - это файл `.git/index` и обновляется он при добавлении/удалении изменений в индекс.

2021-02-04 11:47 UTC, Morganov commented on book/01-introduction/sections/what-is-git.asc
> +Это самая важная часть Git, и это та часть, которая копируется при _клонировании_ репозитория с другого компьютера.
В данном случае запятая перед "и" не ставится.
```suggestion
Это самая важная часть Git и это та часть, которая копируется при _клонировании_ репозитория с другого компьютера.
```

2021-02-05 00:22 UTC, SergeiKuznetsov commented on TRANSLATION_NOTES.asc
> +stashes -- припрятанные
stash, stashes (существительное) -- припрятанные изменения
to stash (глагол) -- припрятать
stashing (существительное, процесс) -- припрятывание
stashed -- припрятано, припрятали

2021-02-05 00:42 UTC, SergeiKuznetsov commented on book/01-introduction/sections/what-is-git.asc
> +Мы подошли к трём основным секциям проекта Git: рабочая копия (working tree), область индексирования (staging area) и каталог Git (Git directory).
Далее идёт фраза:

> Its technical name in Git parlance is the “index”, but the phrase “staging area” works just as well.
> Её техническое название на языке Git -- «индекс», но фраза «область индексирования» также работает.

И в дальнейшем по тексту стараемся использовать слово **индекс**. Как-то так.

2021-02-08 17:14 UTC, Morganov approved these changes

2021-02-08 17:22 UTC, Morganov commented
![redundant_mc](https://user-images.githubusercontent.com/16842235/107256723-e8282000-6a4a-11eb-831c-219161534e96.png)

Пожалуйста, впредь не добавляйте лишних коммитов слияния. Это не только загрязняет историю, но и усложняет её чтение и анализ.
Для выравнивания своей ветки с `master` используйте `git rebase master`.

2021-02-08 17:22 UTC, merged

2021-02-08 21:09 UTC, SergeiKuznetsov commented
> Для выравнивания своей ветки с `master` используйте `git rebase master`.

Значит ни в коем случае не пользоваться интерфейсом GitHub для разрешения конфликтов?
OK

2021-02-08 21:38 UTC, SergeiKuznetsov commented
Буду делать на своей стороне `git rebase upstream/master`, так думаю корректнее.
Затем `git push --force` тематической ветки.