Синхронизация с оригиналом (глава 3)
progit/progit2-ru pull request #371
Opened 2021-02-09 02:00 UTC by SergeiKuznetsov

2021-02-13 07:59 UTC, Morganov requested changes

2021-02-13 07:59 UTC, Morganov commented on book/03-git-branching/sections/branch-management.asc
> +
Пожалуйста, синхронизируя текст книги с оригиналом, переводите изменения.
Такие изменения будут сильно затруднять чтение.

Решение: разделите исправления и добавляемый текст на два ПР. Если вы не готовы переводить сейчас - создайте issue.

2021-02-13 08:15 UTC, SergeiKuznetsov commented on book/03-git-branching/sections/branch-management.asc
> +
Хорошо.
Сначала думал, что английская версия больше из-за того, что много недостающих текстов, но проблема оказалась в иллюстрациях.
Переведу добавленные фрагменты сам.

2021-02-13 08:40 UTC, SergeiKuznetsov commented on book/03-git-branching/sections/branch-management.asc
> +
Или имелись в виду именно изменения, а не новые абзацы?

2021-02-14 20:19 UTC, Morganov requested changes
Упоминание названий веток не соответствуют общепринятому в книге.
Заблокированно https://github.com/progit/progit2/pull/1609

2021-02-14 20:19 UTC, Morganov commented on book/03-git-branching/sections/branch-management.asc
> +
1. Вместо добавления текста на английском, просто обновите статус перевода. Наличие непереведённого текста сильно затрудняет чтение.
2. Добавляйте новый переведённый текст в отдельном ПР. Так проще его верифицировать.
3. Если нет желания или возможности перевести не используя дословный перевод - просто создайте issue, указав чего не хватает.

2021-02-14 23:29 UTC, SergeiKuznetsov commented on book/03-git-branching/sections/branch-management.asc
> +Вы также хотите изменить имя ветки на удаленном сервере (GitHub, GitLab, или другой сервер).
Это не машинный перевод) это у меня проблемы с запятыми.

2021-02-15 03:16 UTC, SergeiKuznetsov commented on book/03-git-branching/sections/branch-management.asc
> +Не переименовывайте ветки, которые все еще используются другими участниками.
OK

2021-02-15 03:19 UTC, SergeiKuznetsov commented on book/03-git-branching/sections/branch-management.asc
> +Предположим, у вас есть ветка с именем _bad-branch-name_, и вы хотите изменить ее на _corrected-branch-name_, сохранив при этом всю историю.
OK

2021-02-21 01:57 UTC, SergeiKuznetsov commented
> Упоминание названий веток не соответствуют общепринятому в книге.
> Заблокированно [progit/progit2#1609](https://github.com/progit/progit2/pull/1609)

Исправил в соответствии с изменениями оригинала

2021-02-28 12:44 UTC, Morganov approved these changes

2021-02-28 17:38 UTC, merged