Синхронизация с оригиналом (глава 4)
progit/progit2-ru pull request #372
Opened 2021-02-09 03:30 UTC by SergeiKuznetsov

2021-02-13 08:01 UTC, Morganov requested changes
Пожалуйста, переводите вносимые изменения и уточнения.

2021-02-13 08:22 UTC, SergeiKuznetsov commented
> Пожалуйста, переводите вносимые изменения и уточнения.

Там где видел, что менялся исходник, там правил перевод.
В остальных местах отмечал в status.json что перевод неполный.

Пройдусь ещё раз.

2021-02-14 09:06 UTC, SergeiKuznetsov commented
Доделано

2021-02-14 20:33 UTC, Morganov requested changes

2021-02-14 20:33 UTC, Morganov commented on book/04-git-server/sections/gitlab.asc
> +К счастью, этот процесс очень хорошо документирован и поддерживается.
"well-documented" означает, что процесс дкументирован хорошо, но совсем не значит, что очень хрошо или полностью.

2021-02-14 20:33 UTC, Morganov commented on book/04-git-server/sections/gitlab.asc
> +* Dockerized пакеты GitLab для использования с Docker.
"Dockerized package" означет "Docker image"
```suggestion
* Официальные образы GitLab для использования с Docker.
```

2021-02-14 20:33 UTC, Morganov commented on book/04-git-server/sections/gitlab.asc
> +* Облачный провайдер, такой как AWS, Google Cloud Platform, Azure, OpenShift и Digital Ocean.
```suggestion
* Облачный провайдер, такой как AWS, Google Cloud Platform, Azure, OpenShift или Digital Ocean.
```

2021-02-14 23:46 UTC, SergeiKuznetsov commented on book/04-git-server/sections/gitlab.asc
> +К счастью, этот процесс очень хорошо документирован и поддерживается.
🆗

2021-03-07 11:55 UTC, Morganov approved these changes

2021-03-07 14:03 UTC, merged