Синхронизация с оригиналом (глава 5)
progit/progit2-ru pull request #373
Opened 2021-02-11 00:25 UTC by SergeiKuznetsov

2021-02-13 09:14 UTC, Morganov requested changes

2021-02-13 09:14 UTC, Morganov commented on book/05-distributed-git/sections/distributed-workflows.asc
> +==== Patterns for Managing Source Code Branches
Требуется перевод

2021-02-13 09:14 UTC, Morganov commented on book/05-distributed-git/sections/maintaining.asc
> +Если кто-то отправил патч, корректно сформированный командой `git send-email`, и вы сохранили его в mbox-формате, то можно указать передать этот файл в качестве аргумента команде `git am`, которая на
```suggestion
Если кто-то отправил патч, корректно сформированный командой `git send-email`, и вы сохранили его в формате mbox, то можно указать передать этот файл в качестве аргумента команде `git am`, которая начнёт применять все найденные в файле патчи.
```

2021-02-13 09:14 UTC, Morganov commented on book/05-distributed-git/sections/maintaining.asc
> +Это начало вывода команды `format-patch`, которая рассматривалась в предыдущем разделе; это так же представляет собой валидный mbox-формат.
```suggestion
Это начало вывода команды `format-patch`, которая рассматривалась в предыдущем разделе; это так же представляет собой валидный формат mbox.
```

2021-02-14 18:53 UTC, SergeiKuznetsov commented on book/05-distributed-git/sections/contributing.asc
> +The blank line separating the summary from the body is critical
Тут по ошибке остался дубль исходного текста.

2021-02-14 21:16 UTC, Morganov requested changes

2021-02-14 21:16 UTC, Morganov commented on book/05-distributed-git/sections/maintaining.asc
> +Rerere означает «reuse recorded resolution» (повторно использовать запомненное решение) -- это способ сокращения ручного разрешения конфликтов.
Git записывает процесс ручного разрешения конфликтов, а не запоминает.
Сокращается не ручное разрешение конфликта, а, по возможности, количество операций, когда это необходимо делать. Отсюда - ускорить.

2021-02-15 04:42 UTC, SergeiKuznetsov commented on book/05-distributed-git/sections/contributing.asc
> +Вы можете захотеть использовать `rebase -i`, чтобы свести свою работу в один коммит или переставить коммиты местами, чтобы сопровождающему было легче проверять патч -- смотрите раздел <<ch07-git-tool
Слово **схлопывать** сбивает с толку.  Это сжатие чего-то одного, а мы объединяем разные коммиты.
Лучше сказать **проверять**, а не **модерировать**.
Книгой мы не **пользуемся** разделом, а читаем или **смотрим**.

2021-02-15 04:59 UTC, SergeiKuznetsov commented on book/05-distributed-git/sections/contributing.asc
> +В этом разделе мы рассмотрели ряд общепринятых рабочих схем и поговорили о различиях между работой в составе небольшой команды над проектами с закрытым исходным кодом и участием в большом публичном п
Схема работы — нормальный термин для перевода понятия Workflow. Он не противоречит "рабочему процессу", а даже более понятнее отражает суть. Считаю в некоторых контекстах лучше перевести так.
Акцент не на процессе как таковом, а на его конфигурации — схеме.

2021-02-15 05:21 UTC, SergeiKuznetsov commented on book/05-distributed-git/sections/contributing.asc
> +Вы знаете, что нужно проверять ошибки в пробелах перед созданием коммита, и можете написать отличное сообщение коммита.
Пробелы же могут быть неправильными! Например лишние двойные или ненужные пробелы в конце строк.
А ещё есть много различных символов означающих разный пробел. 
Переносы строк это тоже white-space. И даже они могут быть с ошибками.

Выше приведён пример проверки ошибок с пробелами в концах строк.
![image](https://user-images.githubusercontent.com/13728212/107908057-9d3c6a00-6f6e-11eb-9abd-26504f4769db.png)

2021-02-15 05:39 UTC, SergeiKuznetsov commented on book/05-distributed-git/sections/maintaining.asc
> +Rerere означает «reuse recorded resolution» (повторно использовать запомненное решение) -- это способ сокращения ручного разрешения конфликтов.
Суть не просто в записывании решений, а в запоминании, чтобы затем использовать.

Запоминание позволяет избежать лишнего ручного разрешения конфликтов, т. е. **сократить их количество**.
А если конфликт не разрешился автоматически, то приходится разрешать руками и сам этот процесс  (ручной) **не ускоряется**.

2021-02-15 21:10 UTC, SergeiKuznetsov commented on book/05-distributed-git/sections/contributing.asc
> +Сообщения коммитов следует писать в повелительном наклонении: «Fix bug» (Исправь баг), а не «Fixed bug» (Исправлен баг) или «Fixes bug» (Исправляет баг).
Тут хотелось бы обсудить формулировки https://github.com/progit/progit2-ru/issues/385

2021-03-07 13:51 UTC, Morganov requested changes

2021-03-07 13:51 UTC, Morganov commented on book/05-distributed-git/sections/contributing.asc
> +В этом разделе мы рассмотрели ряд общепринятых рабочих схем и поговорили о различиях между работой в составе небольшой команды над проектами с закрытым исходным кодом и участием в большом публичном п
"Рабочая схема" - имеет двоякий смысл:
1. Схема работает и в ней нет ошибок (непонятно, схема чего?).
2. Схема что-то описывает, в данном случае рабочий процесс.

Касательно "схема работы", под "работой" в контексте книги часто понимается то, что попадает в коммиты, то есть проделанная прграммистом работа. Возникает путаница.

Если хотите, то:
```suggestion
В этом разделе мы рассмотрели ряд общепринятых схем рабочих процессов и поговорили о различиях между работой в составе небольшой команды над проектами с закрытым исходным кодом и участием в большом публичном проекте.
```

2021-03-07 13:51 UTC, Morganov commented on book/05-distributed-git/sections/contributing.asc
> +Вы можете захотеть использовать `rebase -i`, чтобы свести свою работу в один коммит или переставить коммиты местами, чтобы сопровождающему было легче проверять патч -- смотрите раздел <<ch07-git-tool
> Слово **схлопывать** сбивает с толку. Это сжатие чего-то одного, а мы объединяем разные коммиты.

Всё правильно, схлопываются отдельные коммиты. Однако, можно перефразировать:

```suggestion
Вы можете захотеть использовать `rebase -i`, чтобы объединить несколько коммитов в один или переставить их местами, чтобы сопровождающему было легче проверять патч -- смотрите раздел <<ch07-git-tools#r_rewriting_history>> для получения детальной информации об интерактивном перебазировании.
```

> Лучше сказать **проверять** или рецензировать, а не **модерировать**.

Ок.

> Мы не **пользуемся** разделом, а читаем или **смотрим**.

👍 

`Вы можете захотеть` - дословный перевод.

```suggestion
Возможно, вы захотите использовать `rebase -i`, чтобы свести свою работу в один коммит или переставить коммиты местами, чтобы сопровождающему было легче проверять патч -- смотрите раздел <<ch07-git-tools#r_rewriting_history>> для получения детальной информации об интерактивном перебазировании.
```

В результате, предложение можно изменить так:
```suggestion
Возможно, вы захотите использовать `rebase -i`, чтобы объединить несколько коммитов в один или переставить их местами, чтобы сопровождающему было легче проверять патч -- смотрите раздел <<ch07-git-tools#r_rewriting_history>> для получения детальной информации об интерактивном перебазировании.
```

2021-03-08 01:20 UTC, SergeiKuznetsov commented on book/05-distributed-git/sections/maintaining.asc
> +Rerere означает «reuse recorded resolution» (повторно использовать запомненное решение) -- это способ сокращения ручного разрешения конфликтов.
Оперативная память тут притянута за уши, но пусть будет сохранённое.
За количество операций спасибо, так понятнее звучит.

2021-03-08 05:26 UTC, SergeiKuznetsov commented on book/05-distributed-git/sections/contributing.asc
> +Вы можете захотеть использовать `rebase -i`, чтобы свести свою работу в один коммит или переставить коммиты местами, чтобы сопровождающему было легче проверять патч -- смотрите раздел <<ch07-git-tool
Согласен

2021-03-08 05:30 UTC, SergeiKuznetsov commented on book/05-distributed-git/sections/contributing.asc
> +В этом разделе мы рассмотрели ряд общепринятых рабочих схем и поговорили о различиях между работой в составе небольшой команды над проектами с закрытым исходным кодом и участием в большом публичном п
Да, так лучше.

2021-03-08 05:33 UTC, SergeiKuznetsov commented on book/05-distributed-git/sections/contributing.asc
> +Вы знаете, что нужно проверять ошибки в пробелах перед созданием коммита, и можете написать отличное сообщение коммита.
Запятую убрал

2021-03-12 00:06 UTC, SergeiKuznetsov commented on book/05-distributed-git/sections/maintaining.asc
> +Это начало вывода команды `format-patch`, которая рассматривалась в предыдущем разделе; это так же представляет собой валидный mbox-формат.
Done

2021-03-12 00:07 UTC, SergeiKuznetsov commented on book/05-distributed-git/sections/maintaining.asc
> +Если кто-то отправил патч, корректно сформированный командой `git send-email`, и вы сохранили его в mbox-формате, то можно указать передать этот файл в качестве аргумента команде `git am`, которая на
Done

2021-03-12 00:08 UTC, SergeiKuznetsov commented on book/05-distributed-git/sections/distributed-workflows.asc
> +==== Patterns for Managing Source Code Branches
Done

2021-03-12 07:31 UTC, SergeiKuznetsov commented
Убрал всё, что дублирует https://github.com/progit/progit2-ru/pull/392

2021-03-25 20:34 UTC, merged