Синхронизация с оригиналом (глава 6)
progit/progit2-ru pull request #375
Opened 2021-02-12 03:45 UTC by SergeiKuznetsov

2021-02-13 09:11 UTC, Morganov requested changes

2021-02-13 09:11 UTC, Morganov commented on ch06-github.asc
> +Если вас не интересует использование GitHub для размещения собственных проектов или сотрудничества с другими проектами, размещёнными на нём, вы можете смело перейти к главе «<<ch07-git-tools#ch07-git
кавычки здесь ни к чему, так как ссылка выделяется цветом

2021-02-13 09:11 UTC, Morganov commented on book/06-github/sections/2-contributing.asc
> +[TIP]
Требуется перевод

2021-02-13 09:11 UTC, Morganov commented on book/06-github/sections/2-contributing.asc
> +==== GitHub-версия разметки Markdown
Пожалуйсте, не используйте суффиксы к словам на латинице.

2021-02-13 09:11 UTC, Morganov commented on book/06-github/sections/2-contributing.asc
> +Для «проблемы» или «запроса слияния» в полях описания, комментария, комментария кода и других вы можете использовать так называемую «GitHub-версию разметки Markdown».
Суффик к слову на латинице.

2021-02-13 11:34 UTC, Morganov requested changes

2021-02-13 11:34 UTC, Morganov commented on book/06-github/sections/5-scripting.asc
> +For more information on how to write webhooks and all the different event types you can listen for, go to the GitHub Developer documentation at https://developer.github.com/webhooks/[].
```suggestion
For more information on how to write webhooks and all the different event types you can listen for, go to the GitHub Developer documentation at https://docs.github.com/en/developers/webhooks-and-events/about-webhooks/[].
```

2021-02-14 19:09 UTC, SergeiKuznetsov commented on book/06-github/sections/2-contributing.asc
> +==== GitHub-версия разметки Markdown
Это не суффикс. Это два слова через дефис. 
Такие формы часто используются.
PDF-файлб, SHA-хеш, path-файл, CGI-сценарий, Git-репозиторий...

2021-02-14 19:11 UTC, SergeiKuznetsov commented on book/06-github/sections/2-contributing.asc
> +Для «проблемы» или «запроса слияния» в полях описания, комментария, комментария кода и других вы можете использовать так называемую «GitHub-версию разметки Markdown».
нет

2021-02-15 02:34 UTC, SergeiKuznetsov commented on ch06-github.asc
> +Если вас не интересует использование GitHub для размещения собственных проектов или сотрудничества с другими проектами, размещёнными на нём, вы можете смело перейти к главе «<<ch07-git-tools#ch07-git
Согласен. Кавычки лишние.
Но фразы типа:

> вы можете смело перейти к Инструменты Git.

Стоит поправить. Выглядит странно.

Возможны два варианта

1. перейти к главе Инстументы Git
2. перейти к инструментам Git

2021-02-15 02:49 UTC, SergeiKuznetsov commented on book/06-github/sections/2-contributing.asc
> +[TIP]
готово

2021-02-15 02:52 UTC, SergeiKuznetsov commented on book/06-github/sections/5-scripting.asc
> +For more information on how to write webhooks and all the different event types you can listen for, go to the GitHub Developer documentation at https://developer.github.com/webhooks/[].
Какой смысл избавляться от короткой ссылки? Чтобы читателям бумажной версии усложнить поиск страницы?

2021-03-12 07:30 UTC, SergeiKuznetsov commented
Убрал всё, что дублирует https://github.com/progit/progit2-ru/pull/392

2021-03-25 20:32 UTC, merged