Синхронизация с оригиналом (глава 7)
progit/progit2-ru pull request #376
Opened 2021-02-13 05:33 UTC by SergeiKuznetsov

2021-02-13 08:59 UTC, Morganov requested changes

2021-02-13 08:59 UTC, Morganov commented on book/07-git-tools/sections/rewriting-history.asc
> +Так как коммиты содержат значения SHA-1-хешей их родителей, эта команда изменяет хеш SHA-1 каждого коммита в вашей истории, а не только тех, которые соответствовали адресам электронной почты.
"SHA-1 хеш коммита" - указывает на то, какой хеш (его тип)
"хеш SHA-1 коммита" - указывает на то, что SHA-1 является объектом хэширования, что вводит в заблуждение.

2021-02-13 08:59 UTC, Morganov commented on book/07-git-tools/sections/subtree-merges.asc
> +Это дает нам возможность использовать такую же рабочую схему, как и в случае с подмодулями, но при этом без использования  подмодулей (которые мы рассмотрим в разделе «<<r_git_submodules>>»).
```suggestion
Это даёт нам возможность использовать такую же рабочую схему, как и в случае с подмодулями, но при этом без использования  подмодулей (которые мы рассмотрим в разделе «<<r_git_submodules>>»).
```

2021-02-13 08:59 UTC, Morganov commented on book/07-git-tools/sections/submodules.asc
> +===== Pulling Upstream Changes from the Project Remote
Требуется перевод

2021-02-13 08:59 UTC, Morganov commented on book/07-git-tools/sections/submodules.asc
> +Newer Git versions (Git >= 2.13) simplify all this by adding the `--recurse-submodules` flag to the `git checkout` command, which takes care of placing the submodules in the right state for the branc
Требуется перевод

2021-02-13 08:59 UTC, Morganov commented on book/07-git-tools/sections/revision-selection.asc
> +If you dedicate several thousands of dollars' worth of computing power to it, it is possible to synthesize two files with the same hash, as proven on https://shattered.io/[] in February 2017.
Требуется перевод.

2021-02-13 08:59 UTC, Morganov commented on book/07-git-tools/sections/revision-selection.asc
> +[TIP]
Требуется перевод

2021-02-13 08:59 UTC, Morganov commented on book/07-git-tools/sections/revision-selection.asc
> +===== Множественная выборка
Здесть речь идёт про использование точек.

2021-02-13 20:34 UTC, SergeiKuznetsov commented on book/07-git-tools/sections/rewriting-history.asc
> +Так как коммиты содержат значения SHA-1-хешей их родителей, эта команда изменяет хеш SHA-1 каждого коммита в вашей истории, а не только тех, которые соответствовали адресам электронной почты.
Тогда нужен дефис SHA-1-хэш

2021-02-14 21:22 UTC, Morganov commented on book/07-git-tools/sections/rewriting-history.asc
> +Так как коммиты содержат значения SHA-1-хешей их родителей, эта команда изменяет хеш SHA-1 каждого коммита в вашей истории, а не только тех, которые соответствовали адресам электронной почты.
Почему?

2021-02-14 21:35 UTC, SergeiKuznetsov commented on book/07-git-tools/sections/rewriting-history.asc
> +Так как коммиты содержат значения SHA-1-хешей их родителей, эта команда изменяет хеш SHA-1 каждого коммита в вашей истории, а не только тех, которые соответствовали адресам электронной почты.
Грамматика русского  языка. 
Через дефис пишутся сложные существительные из двух слов без соединительных гласных

2021-02-15 06:12 UTC, SergeiKuznetsov commented on book/07-git-tools/sections/rewriting-history.asc
> +Так как коммиты содержат значения SHA-1-хешей их родителей, эта команда изменяет хеш SHA-1 каждого коммита в вашей истории, а не только тех, которые соответствовали адресам электронной почты.
Меня не вводит в заблуждение фраза `хеш SHA-1 коммита`
Понятно что хеш именно коммита.
В книге иногда пишут просто `SHA-1 коммита`
Можно использовать более привычные формулировки, например `контрольная сумма коммита`

2021-02-15 19:14 UTC, SergeiKuznetsov commented on book/07-git-tools/sections/revision-selection.asc
> +===== Множественная выборка
Не соглашусь.
В этом разделе рассматривается альтернативный синтаксис без использования точек.
И заголовок "Множество точек" наоборот сбивает с толку.

Этот синтаксис удобен, так как позволяет указывать в запросе более двух ссылок, чего не позволяет сделать синтаксис с точками.

2021-02-15 19:16 UTC, SergeiKuznetsov commented on book/07-git-tools/sections/rewriting-history.asc
> -=== Исправление истории
История не обязательно должна быть неправильной, чтобы мы захотели её изменить. Перезапись — более корректный термин.

2021-02-15 20:36 UTC, SergeiKuznetsov commented on status.json
> +      "sections/submodules.asc": 80,
Добавленные разделы отправлю в другой запрос на изменение

2021-02-15 20:38 UTC, SergeiKuznetsov commented on book/07-git-tools/sections/submodules.asc
> +Newer Git versions (Git >= 2.13) simplify all this by adding the `--recurse-submodules` flag to the `git checkout` command, which takes care of placing the submodules in the right state for the branc
Пока убрал отсюда вставку

2021-02-15 20:38 UTC, SergeiKuznetsov commented on book/07-git-tools/sections/revision-selection.asc
> +If you dedicate several thousands of dollars' worth of computing power to it, it is possible to synthesize two files with the same hash, as proven on https://shattered.io/[] in February 2017.
Переведено

2021-03-12 07:30 UTC, SergeiKuznetsov commented
Убрал всё, что дублирует https://github.com/progit/progit2-ru/pull/392

2021-04-04 14:54 UTC, Morganov requested changes

2021-04-04 14:54 UTC, Morganov commented on book/07-git-tools/sections/revision-selection.asc
> +Служебные команды будут подробно рассматриваться в главе <<ch10-git-internals#ch10-git-internals>>;  в основном, команда `rev-parse` существует для низкоуровневых операций и не предназначена для ежед
```suggestion
Служебные команды подробно рассматрены в главе <<ch10-git-internals#ch10-git-internals>>;  в основном, команда `rev-parse` существует для низкоуровневых операций и не предназначена для ежедневного использования.
```

2021-04-04 14:54 UTC, Morganov commented on book/07-git-tools/sections/revision-selection.asc
> +Одна из вещей, которую Git выполняет в фоновом режиме, пока вы работаете -- это ведение «журнала ссылок» -- журнала, в котором хранятся ссылки указателей HEAD и веток за последние несколько месяцев.
Пытаюсь понять. HEAD и ветки - это ссылки. Ссылки указывают на коммиты, т.е. являются указателями.
Непонятно: "хранятся ссылки указателей HEAD и веток".

"a log of where your HEAD and branch references have been" - дословно: "лог записей, где были HEAD и ветки".

На мой взгляд, предыдущий вариант более понятный.

2021-04-04 14:54 UTC, Morganov commented on book/07-git-tools/sections/revision-selection.asc
> +В частности, чтобы увидеть где была ветка `master` вчера, следует написать:
Ниже приведена команда. Ещё ниже - предложение, которое ссылается на **команду**.

2021-04-06 06:56 UTC, SergeiKuznetsov commented on book/07-git-tools/sections/revision-selection.asc
> +Служебные команды будут подробно рассматриваться в главе <<ch10-git-internals#ch10-git-internals>>;  в основном, команда `rev-parse` существует для низкоуровневых операций и не предназначена для ежед
OK. Только рассмОтрены.

2021-04-06 07:29 UTC, SergeiKuznetsov commented on book/07-git-tools/sections/revision-selection.asc
> +В частности, чтобы увидеть где была ветка `master` вчера, следует написать:
Поправил

2021-04-06 07:31 UTC, SergeiKuznetsov commented on book/07-git-tools/sections/revision-selection.asc
> +Одна из вещей, которую Git выполняет в фоновом режиме, пока вы работаете -- это ведение «журнала ссылок» -- журнала, в котором хранятся ссылки указателей HEAD и веток за последние несколько месяцев.
Переписал немного иначе. Предыдущий вариант какой-то неправильный.

2021-06-06 05:43 UTC, closed without merging