Update PNGs
progit/progit2-ru pull request #382
Opened 2021-02-14 04:32 UTC by SergeiKuznetsov

Exported from progit.sketch with 3 × size

* [x] advance-master.png
* [x] basic-merging-2.png

2021-02-14 19:18 UTC, Morganov requested changes
Буква "g" в слове "testing" на картинке "advance-master.png" отображается не полностью.

2021-02-14 21:24 UTC, SergeiKuznetsov commented
> Буква "g" в слове "testing" на картинке "advance-master.png" отображается не полностью.

Есть такая проблема. В макете сейчас все надписи съехали чуть вниз. 
В версии перед сменой шрифта диаграммы выглядят корректно. Наверное PNG создавались с шрифтом Menlo.
Посмотрю внимательней.

2021-02-15 02:14 UTC, SergeiKuznetsov commented
Пересохранил из состояния коммита 1eff741
До того, как шрифт Menlo заменили на другой.
Теперь выглядит хорошо.

2021-02-16 18:20 UTC, Morganov approved these changes
Превосходно!

2021-02-16 20:12 UTC, merged