Синхронизация с оригиналом (глава 8)
progit/progit2-ru pull request #383
Opened 2021-02-14 06:09 UTC by SergeiKuznetsov

2021-02-14 19:12 UTC, Morganov requested changes

2021-02-14 19:12 UTC, Morganov commented on book/08-customizing-git/sections/attributes.asc
> +Для начала, вы можете автоматически добавлять SHA-1-хеш объекта в поле `$Id$`.
Здесь и далее, не используйте суффиксы со словами на латинице (`SHA-1` является названием алгоритма хеширования), а то глаз запинается.

2021-02-14 22:04 UTC, SergeiKuznetsov commented on book/08-customizing-git/sections/attributes.asc
> +Для начала, вы можете автоматически добавлять SHA-1-хеш объекта в поле `$Id$`.
Не соглашусь. Какие суффиксы? Тут сложное слово, которое нужно писать через дефис.  Во фразе говорится не про алгоритм хеширования а про конкретный объект — SHA-1-хеш. Возможно по-русски стоит писать SHA-хеш без уточнения версии алгоритма. Но без дефиса точно глаз запинается.

> Дефис употребляется в составе письменных эквивалентов сложных слов, часть которых передается цифрой, буквой или буквами (в том числе нерусского алфавита) или иным начертанием (даже таким, которое невозможно «прочесть»), напр.: 25-процентный, 150-летие, 300-миллионный, 5 1/2-тысячный, Т-образный, IBM-совместимый, γ-активный, «S-образное движение ловкого тела» (Купр.), ww-образные трубки.


http://new.gramota.ru/spravka/buro/search-answer?s=286438

2021-02-15 04:13 UTC, SergeiKuznetsov commented on book/08-customizing-git/sections/attributes.asc
> +Это фактически создает хорошие текстовые версии файлов Word, прежде чем пытаться их сравнить.
OK

2021-02-15 04:13 UTC, SergeiKuznetsov commented on book/08-customizing-git/sections/attributes.asc
> +Теперь Git знает, что при сравнении двух версий файлов `.docx`, он должен пропустить эти файлы через фильтр «word», который определён в программе `docx2txt`.
OK

2021-02-16 20:37 UTC, Morganov commented on book/08-customizing-git/sections/attributes.asc
> +Для начала, вы можете автоматически добавлять SHA-1-хеш объекта в поле `$Id$`.
В данной фразе идёт речь про хеш объекта, а не про хеш как объект.
В контексте данной книги хеш представляет собой строку фиксированной длины, полученную путём обработки содержимого файла по алгоритму SHA-1. Соответственно указанному правилу, фразу можно преобразовать в
```
Для начала, вы можете автоматически добавлять 20-байтный хеш объекта в поле `$Id$`.
```
но, к сожалению, так становится непонятно какой алгоритм херирования используется.
Знать про алгоритм важно, потому как Git позиционируется как "инструмент для создания" систем контроля версий.

Кроме SHA-1, существуют ещё алгоритмы SHA-256, SHA-512 и так далее. К тому же, в Git существует экспериментальная поддержка алгоритма SHA-256, поэтому избавиться от уточнения версии алгоритма не выйдет.

2021-02-16 23:37 UTC, SergeiKuznetsov commented on book/08-customizing-git/sections/attributes.asc
> +Для начала, вы можете автоматически добавлять SHA-1-хеш объекта в поле `$Id$`.
Разве **хеш объекта** и **хеш как объект** это не одна и та же сущность? ))
В чём разница?

В любом случае писать через пробел неграмотно.
Даже википедия говорит, что SHA-1 используется в Git для идентификации каждого объекта по **SHA-1-хешу** от хранимой в объекте информации.

2021-03-12 07:29 UTC, SergeiKuznetsov commented
Убрал всё, что дублирует https://github.com/progit/progit2-ru/pull/392

2021-03-25 20:35 UTC, merged