Обновить инструкции по сборке в README
progit/progit2-ru pull request #386
Opened 2021-02-21 22:58 UTC by SergeiKuznetsov

2021-02-26 20:49 UTC, SergeiKuznetsov commented
Но нужно ещё обновить сборщик, чтобы новые команды заработали 
progit/progit2/pull/1598

2021-02-28 11:42 UTC, Morganov requested changes

2021-02-28 11:42 UTC, Morganov commented on Rakefile
> +      header_hash = header.scan(/[a-f0-9]{7,}/).join
Пожалуйста, не копируйте скрипты сборки из оригинального репозитория только потому, что они там изменились.
Текущий вариант совсем "сырой" и требует доработки, особенно идея с добавлением хеша в текст книги.

2021-03-01 00:36 UTC, SergeiKuznetsov commented on Rakefile
> +      header_hash = header.scan(/[a-f0-9]{7,}/).join
Это не изменение ради изменения, а реально полезная доработка.
Мне не хватало возможности быстро собрать только **один из форматов** без долгих проверок.
Предложенная доработка незначительна на самом деле и делает сборщик более структурированным.
 
И наш README сейчас довольно устарел и вводит в заблуждение.

Над contributors.txt конечно надо дальше работать.
Мне вот не нравится как список ломается сейчас  в pdf и epub. Выглядит мягко говоря неаккуратно.
И ещё наш список участников недостаточно длинный, чтобы сборщик его разделил на несколько страниц, и недостаточно короткий, чтобы уместиться вместе с вводным текстом на одной странице.
В итоге  список ушел на отдельную страницу.

Я поменял параметры, чтобы выводилось максимум в две колонки. Тогда не ломается вёрстка нигде, даже в epub. 

Предлагаю пока одобрить мой вариант, а дальше подумаем как улучшить.
По хорошему тут стоит упомянуть и тех, кто вкладывался в английскую книгу. Ведь мы используем их труды у себя.

2021-03-01 05:42 UTC, SergeiKuznetsov commented
Убрал спорные моменты из скрипта.
Оставил только новые команды.

2021-03-07 13:56 UTC, Morganov requested changes

2021-03-07 13:56 UTC, Morganov commented on README.asc
> +Чтобы исправить ошибку или добавить что-то новое в этот репозиторий, вам нужно открыть запрос на изменение (Pull Request) на GitHub.
```suggestion
Чтобы исправить ошибку или добавить что-то новое в этот репозиторий, вам нужно открыть запрос на слияние (Pull Request) на GitHub.
```

2021-03-07 13:56 UTC, Morganov commented on README.asc
> +Текущую сборку можно найти по адресу https://git-scm.com/book/ru/v2.
```suggestion
Текущую сборку можно найти на странице https://git-scm.com/book/ru/v2.
```

2021-03-07 14:02 UTC, Morganov commented on Rakefile
> +      header_hash = header.scan(/[a-f0-9]{7,}/).join
Посмотрите #391. Там же добавлен изменение по размеру колонок для contributors.

> По хорошему тут стоит упомянуть и тех, кто вкладывался в английскую книгу. Ведь мы используем их труды у себя.

Все, кто вносит свой вклад в английскую версию, не вносят никакого вклада в перевод её на русский язык.
При этом, ряд участников из англ версии всё же присутствуют в списке.

2021-03-07 23:59 UTC, SergeiKuznetsov commented on README.asc
> +Чтобы исправить ошибку или добавить что-то новое в этот репозиторий, вам нужно открыть запрос на изменение (Pull Request) на GitHub.
Согласен. В одних системах называется Pull Request, в других Merge Request. 
Суть одинакова и смысл в слиянии.

2021-03-08 00:16 UTC, SergeiKuznetsov commented on Rakefile
> +      header_hash = header.scan(/[a-f0-9]{7,}/).join
Да, я увидел #391. Уберу у себя скрипт сборки.

А насчёт английских авторов спорный вопрос. Их вклад всё равно попадает в русскую версию, но уже в переводе. И некоторые у нас в списке есть только потому, что переводчики не забыли их упомянуть в описании коммитов как соавторов изменений. 

Наверное нет смысла вытаскивать участников из английской версии, но в наших правках стоит упоминать первоначальных авторов правки.

2021-03-08 00:18 UTC, SergeiKuznetsov commented on README.asc
> +Текущую сборку можно найти по адресу https://git-scm.com/book/ru/v2.
OK

2021-03-12 07:28 UTC, SergeiKuznetsov commented
Оставил только актуализацию README

2021-04-04 14:07 UTC, Morganov requested changes

2021-04-04 14:07 UTC, Morganov commented on README.asc
> +Используя команды ниже, вы сможете получить HTML-, EPUB- и PDF-файлы:
```suggestion
Используя команды ниже, вы сможете получить книгу в форматах HTML, EPUB и PDF.
```

2021-04-06 06:15 UTC, SergeiKuznetsov commented on README.asc
> +Раньше мы могли собирать файлы .mobi (Kindle), но сейчас не можем, см. https://github.com/progit/progit2/issues/1496[#1496] для получения дополнительной информации.
Не вижу противоречий в тексте. Раньше могли .mobi, теперь не можем. Зачем это умалчивать?
А что за другой формат?

2021-04-06 06:28 UTC, SergeiKuznetsov commented on README.asc
> +Используя команды ниже, вы сможете получить HTML-, EPUB- и PDF-файлы:
OK

2021-05-02 20:51 UTC, Morganov requested changes

2021-05-02 20:51 UTC, Morganov commented on README.asc
> +Раньше мы могли собирать файлы .mobi (Kindle), но сейчас не можем, см. https://github.com/progit/progit2/issues/1496[#1496] для получения дополнительной информации.
Нет смысла писать про формат, который не поддерживается и не будет поддерживаться.
Другой формат - тоже EPUB, генерируется тем же модулем, что раньше генерировал mobi

2021-05-02 21:37 UTC, SergeiKuznetsov commented on README.asc
> +Раньше мы могли собирать файлы .mobi (Kindle), но сейчас не можем, см. https://github.com/progit/progit2/issues/1496[#1496] для получения дополнительной информации.
Удалил абзац

2021-05-11 10:57 UTC, Morganov approved these changes

2021-05-11 11:24 UTC, merged