Исправить примеры консольных сообщений
progit/progit2-ru pull request #401
Opened 2021-03-23 06:39 UTC by SergeiKuznetsov

2021-04-04 08:32 UTC, Morganov requested changes

2021-04-04 08:32 UTC, Morganov commented on book/10-git-internals/sections/transfer-protocols.asc
> +00ab6c5f0e45abd7832bf23074a333f739977c9e8188 refs/heads/master□report-status \
```suggestion
00ab6c5f0e45abd7832bf23074a333f739977c9e8188 refs/heads/master\0report-status \
```

2021-04-04 08:32 UTC, Morganov commented on book/10-git-internals/sections/transfer-protocols.asc
> +00dfca82a6dff817ec66f44342007202690a93763949 HEAD□multi_ack thin-pack \
```suggestion
00dfca82a6dff817ec66f44342007202690a93763949 HEAD\0multi_ack thin-pack \
```

2021-04-04 08:32 UTC, Morganov commented on book/10-git-internals/sections/transfer-protocols.asc
> +00a5ca82a6dff817ec66f4437202690a93763949 refs/heads/master□report-status \
```suggestion
00a5ca82a6dff817ec66f4437202690a93763949 refs/heads/master\0report-status \
```

2021-04-04 08:32 UTC, Morganov commented on book/07-git-tools/sections/revision-selection.asc
> +.Думайте о reflog как о Git-версии истории командной оболочки
```suggestion
.Думайте о reflog как о версии Git истории командной строки
```

2021-04-04 08:43 UTC, SergeiKuznetsov commented on book/06-github/sections/2-contributing.asc
> +<1> Добавить исходный репозиторий как удалённый и дать ему имя.
Не соглашусь. В оригинале «give it a name», никакого другого имени.
Имя по умолчанию «origin» запросто может ещё не существовать и ничего не мешает нам его задать через git remote add
Не надо выдумывать другие смыслы оригинального текста.

2021-04-04 09:09 UTC, SergeiKuznetsov commented on book/10-git-internals/sections/transfer-protocols.asc
> +00ab6c5f0e45abd7832bf23074a333f739977c9e8188 refs/heads/master□report-status \
Авторы решили что символ белого квадрата тут будет правильней. Все вопросы к ним.
https://github.com/progit/progit2/commit/418db6a83a54c6620e7da8fbb3f3c3b90494fae4

2021-04-04 09:09 UTC, SergeiKuznetsov commented on book/10-git-internals/sections/transfer-protocols.asc
> +00dfca82a6dff817ec66f44342007202690a93763949 HEAD□multi_ack thin-pack \
https://github.com/progit/progit2/commit/418db6a83a54c6620e7da8fbb3f3c3b90494fae4

2021-04-04 09:24 UTC, SergeiKuznetsov commented on book/09-git-and-other-scms/sections/import-bzr.asc
> +$ sudo python setup.py install --record=files.txt   # установит плагин
Выравнивание начала комментария в одну колонку приводит к бессмысленному удлинению строк листинга и переносам длинных строк. В оригинале это поправлено. Я только синхронизировал.

2021-04-04 09:24 UTC, SergeiKuznetsov commented on book/06-github/sections/2-contributing.asc
> +<2> Получить ветки progit, в частности `master`.
Даже лучше так:
Получить ветки репозитория `progit`, в частности ветку `master`.
В оригинале там «ветки прогита», но мы не склоняем латиницу, поэтому нужны вспомогательные слова.
Я подумаю над этим местом ещё раз.

2021-04-04 09:25 UTC, SergeiKuznetsov commented on book/08-customizing-git/sections/policy.asc
> +$user    = ENV['USER']
Наверное по аналогии с 31 строкой. Не вижу смысла менять авторское оформление.

2021-04-04 09:48 UTC, SergeiKuznetsov commented on book/07-git-tools/sections/revision-selection.asc
> +.Думайте о reflog как о Git-версии истории командной оболочки
Так сложнее понять. Откуда у вас боязнь составных слов, которые пишутся через дефис? 
Они нормальны и повсеместно используются. PR-служба, PIN-код, SIM-карта, SMS-сообщение, e-mail-адрес и т. п. И не только со смешанным алфавитом https://orfogrammka.ru/правила_русской_орфографии_и_пунктуации_лопатин/правила_слитного_дефисного_и_раздельного_написания/#id-4Правиласлитногодефисногоираздельногонаписания-§117
Нет смысла вычищать их из текстов.
Причём удаление дефиса и перемена местами слов меняет смысл.
Git-версия ≠ версия Git
В первом случае мы понимаем что речь про гитовую версию чего-то.
А во втором можно подумать, что имеется в виду версия самого Git

2021-04-04 13:38 UTC, Morganov commented on book/06-github/sections/2-contributing.asc
> +<1> Добавить исходный репозиторий как удалённый и дать ему имя.
Не соглашусь с дословным переводом.
Потрудитесь прочитать весь раздел "Keep your GitHub public repository up-to-date". Речь про работу с двумя удалёнными репозиториями.

2021-04-04 13:41 UTC, Morganov commented on book/06-github/sections/2-contributing.asc
> +<2> Получить ветки progit, в частности `master`.
В оригинале "указатели на ветки из удалённого репозитория с именем progit". Проблема в том, что во время выполнения команды `fetch` происходит получение не только веток. Другими словами, список пояснений требует доработки, поэтому не стоит переводить его дословно.
Идеальный вариант - исправить в оригинале.

2021-04-04 13:42 UTC, Morganov commented on book/08-customizing-git/sections/policy.asc
> +$user    = ENV['USER']
Не вижу смысла вносить это исправление.

2021-04-04 13:44 UTC, Morganov commented on book/09-git-and-other-scms/sections/import-bzr.asc
> +$ sudo python setup.py install --record=files.txt   # установит плагин
В таком виде чтение листинга затрудняется.
Думаю, можно применить подход с нумерацией строк и последующим списком пояснений ниже.

2021-04-04 13:47 UTC, Morganov commented on book/10-git-internals/sections/transfer-protocols.asc
> +00ab6c5f0e45abd7832bf23074a333f739977c9e8188 refs/heads/master□report-status \
Это ошибка. Для воспроизведения ситуации воспользуйтесь переменной окружения GIT_TRACE_PACKET или обратитесь к разделу https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables.

К тому же, в оригинале "белый квадрат" не везде, где должен присутствовать символ с кодом \0.

Это ещё одно доказательство того, что не следует слепо тянуть все изменения из оригинала.

2021-04-04 14:02 UTC, Morganov requested changes

2021-04-04 14:02 UTC, Morganov commented on book/07-git-tools/sections/revision-selection.asc
> +.Думайте о reflog как о Git-версии истории командной оболочки
Исправление скопировано из строки ниже.

Вот мой вариант:
```suggestion
.Воспринимайте reflog Git как историю командной строки
```

2021-04-06 05:50 UTC, SergeiKuznetsov commented on book/09-git-and-other-scms/sections/import-bzr.asc
> +$ sudo python setup.py install --record=files.txt   # установит плагин
В таком виде читать легче
![image](https://user-images.githubusercontent.com/13728212/113664265-50b50700-9660-11eb-993b-d7e8de824dd3.png)
в отличие от старого варианта
![image](https://user-images.githubusercontent.com/13728212/113664650-f799a300-9660-11eb-926b-e74f70fb2589.png)

> Думаю, можно применить подход с нумерацией строк и последующим списком пояснений ниже.
Возможно. Но сначала в оригинале книги это сделать.

2021-04-06 06:10 UTC, SergeiKuznetsov commented on book/06-github/sections/2-contributing.asc
> +<2> Получить ветки progit, в частности `master`.
Поправил немного весь раздел

2021-04-06 06:10 UTC, SergeiKuznetsov commented on book/08-customizing-git/sections/policy.asc
> +$user    = ENV['USER']
Ладно, не понимаю зачем, но отменил исправление.

2021-04-06 06:11 UTC, SergeiKuznetsov commented on book/10-git-internals/sections/transfer-protocols.asc
> +00ab6c5f0e45abd7832bf23074a333f739977c9e8188 refs/heads/master□report-status \
Мне не принципиально. Не буду эти места править тогда.

2021-04-06 06:12 UTC, SergeiKuznetsov commented on book/07-git-tools/sections/revision-selection.asc
> +.Думайте о reflog как о Git-версии истории командной оболочки
Поправил перевод

2021-05-02 20:55 UTC, Morganov approved these changes

2021-05-02 21:06 UTC, merged